
apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      image: chitra2409/posts:0.0.1
       

---

apiVersion: v1
kind: Pod
metadata:
  name: query
spec:
  containers:
    - name: query
      image: chitra2409/query:0.0.1

---

apiVersion: v1
kind: Pod
metadata:
  name: event-bus
spec:
  containers:
    - name: event-bus
      image: chitra2409/pevent-bus:0.0.1

---

apiVersion: v1
kind: Pod
metadata:
  name: comments
spec:
  containers:
    - name: comments
      image: chitra2409/comments:0.0.1

---

apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
    - name: client
      image: chitra2409/client:0.0.2
      ports:
      - containerPort: 3000

